<Project>

	<PropertyGroup>
		<Version>1.0.0</Version>
		<Authors>xiaolong233</Authors>
		<Description>这是辅助 .NET 开发的小类库～ 平时顺手攒的小零件都在这儿了，希望能帮你少敲几行重复代码！(｡•̀ᴗ-)✧</Description>
		<PackageReadmeFile>NuGet.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/xiaolong233/noelle-net</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>dotnet;NoelleNet;ddd;eventbus;efcore;cap;auditing;uow;aspnetcore;mediatr;fluentvalidation</PackageTags>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>noelle_net.png</PackageIcon>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\NuGet.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\..\noelle_net.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>