<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\CommonProps.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace />
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DotNetCore.CAP" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NoelleNet.EventBus\NoelleNet.EventBus.csproj" />
	</ItemGroup>

</Project>
